version: '3'

services:
  database:
    image: postgres:latest
    hostname: database
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      POSTGRES_DB: crebito
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d crebito -q -t 1'"]
      start_period: 1s
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "350MB"

  api01: &api
    image: clebsantos/rinha-de-backend-2024-dart:latest
    hostname: api01
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_PASS: docker
      DB_USER: postgres
      DB_SCHEMA: crebito
      PORT: 8080
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "70MB"
    depends_on:
      database:
        condition: service_healthy

  api02:
    <<: *api 
    hostname: api02
    depends_on:
      database:
        condition: service_healthy

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "60MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1