name: rinha_de_backend_2024_dart
description: Aplicação para a competição Rinha de Backend 2024
version: 1.0.0
homepage: https://github.com/clebsonsantos/rinha-de-backend-2024-dart

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  dotenv: ^4.2.0
  postgres: ^2.6.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
