name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  DOCKER_IMAGE_VERSION: 1.0.0

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Build and push Docker Image
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          clebsantos/rinha-de-backend-2024-dart:v${{ env.DOCKER_IMAGE_VERSION }}
          clebsantos/rinha-de-backend-2024-dart:latest
